# Generated by Django 6.0.6 on 2026-06-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Продукти", "Продукти"),
                    ("Транспорт", "Транспорт"),
                    ("Розваги", "Розваги"),
                    ("Підписки", "Підписки"),
                    ("Одяг", "Одяг"),
                    ("Зарплата", "Зарплата"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Дохід"), ("expense", "Витрата")], max_length=10
            ),
        ),
    ]
