# Generated by Django 6.0.6 on 2026-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("Продукти", "Продукти"),
                    ("Транспорт", "Транспорт"),
                    ("Розваги", "Розваги"),
                    ("Підписки", "Підписки"),
                    ("Одяг", "Одяг"),
                    ("Інше", "Інше"),
                    ("Зарплата", "Зарплата"),
                    ("Премія", "Премія"),
                    ("Подарунок", "Подарунок"),
                ],
                max_length=100,
            ),
        ),
    ]
