# Generated by Django 6.0.6 on 2026-06-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_transaction_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Накопичення на Ford Fusion", max_length=200
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, default=500000, max_digits=10
                    ),
                ),
            ],
        ),
    ]
